Vagrant.configure("2") do |config|
  # Path to the private key to use to SSH into the guest machine. By default this is the insecure private key that ships with Vagrant.
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  # Tells Vagrant to not insert new keypair for SSH
  config.ssh.insert_key = false
  # This line assumes that your public ssh key is located in $HOME/.ssh/id_rsa.pub and will be used.
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "ansible" do |ansible|
        ansible.become = true
        ansible.verbose = "v"
        ansible.playbook = "./users-playbook.yml"
  # Guest machine OS to use.
  vgt_boxes = [['debian','bullseye64',2]]

vgt_boxes.each { |(a, b, c)|
    config.vm.define "#{b}" do |ans|
    ans.vm.box = "#{a}/#{b}"
    ans.vm.hostname = "#{b}"
    # Will create the following private network in Virtualbox
    ans.vm.network "private_network", ip: "192.168.62.#{c}"
    ans.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.name = "vagrant_ansible_tests_#{b}"
    end
  end }
end
